name: Image

on:
  release:
    types: [ published ]
  workflow_dispatch:

# Set permissions to allow deployment to ghcr.io
permissions:
  packages: write
  contents: read

# Prevent concurrent builds
concurrency:
  group: image-${{ github.ref }}
  cancel-in-progress: false

jobs:
  push:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
